### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by a351816193** [bosichong/PrimarySchoolMathematics#1]
运行提示缺少模块
`File "App.py", line 44, in <module>
    import wx`

**Comment by hellodabin** [comment]
一样的问题

**Comment by brucezlata** [comment]
python3.6 windows平台，一切完美运行

**Comment by bosichong** [comment]
2 安装.docx模块,安装wxPython模块 安装方法：

pip3 install python-docx

pip3 install wxpython
