### ISSUE TITLE
Cannot clone in windows due to invalid path

### ISSUE THREAD

**Issue by brucezlata** [bosichong/PrimarySchoolMathematics#2]
Cloning into 'PrimarySchoolMathematics'...
remote: Enumerating objects: 285, done.
remote: Total 285 (delta 0), reused 0 (delta 0), pack-reused 285
Receiving objects: 100% (285/285), 138.13 KiB | 260.00 KiB/s, done.
Resolving deltas: 100% (175/175), done.
error: invalid path '布局文件/:Users:mac:PycharmProjects:PrimarySchoolMath:Users:mac.wxg'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

root cause:
colon is reserved char. 
Use any character in the current code page for a name, including Unicode characters and characters in the extended character set (128–255), except for the following:

The following reserved characters:

< (less than)
(greater than)

**### : (colon)**
" (double quote)
/ (forward slash)
\ (backslash)
| (vertical bar or pipe)
? (question mark)
(asterisk)

**Comment by brucezlata** [comment]
error: invalid path '布局文件/:Users:mac:PycharmProjects:PrimarySchoolMath:Users:mac.wxg'

Can you change the naming of this file?

**Comment by bosichong** [comment]
The running of the program has nothing to do with this file,
If you need this file, I can send it to your mailbox,
Do you need it?

**Comment by bosichong** [comment]
I have changed the name of that file to English

**Comment by brucezlata** [comment]
The root cause is character : (colon). It is reserved character for windows OS. Cannot name a file name using colon.

So, could you please change name of :Users:mac:PycharmProjects:PrimarySchoolMath:Users:mac.wxg to block windows git clone?

**Comment by brucezlata** [comment]
Or delete :Users:mac:PycharmProjects:PrimarySchoolMath:Users:mac.wxg

**Comment by bosichong** [comment]
The file name has been modified. Try clone again (*￣︶￣)

**Comment by bosichong** [comment]
如果还是不能clone，你可以试试下载压缩的.zip包

**Comment by brucezlata** [comment]
Problem was solved.
