### ISSUE TITLE
新需求，增加下载功能

### ISSUE THREAD

**Issue by xflcx1991** [bosichong/PrimarySchoolMathematics#6]
生成的结果在docx目录下，这不方便远程部署。能否提供下载功能，或者就为docx目录搞成http可浏览的（文件服务器）提供下载。目前是我通过 python -m http.server 来临时为远程提供服务

**Comment by bosichong** [comment]
这个可以有,我抽口研究一下.

**Comment by xflcx1991** [comment]
> 这个可以有,我抽空研究一下.

感谢，捐了大杯拿铁的钱，请研究一下，期待尽早上线。

**Comment by bosichong** [comment]
才看到.多谢了老板,我尽力.

**Comment by bosichong** [comment]
> 感谢，捐了大杯拿铁的钱，请研究一下，期待尽早上线。

添加了下载的功能,更新到master了.
