### ISSUE TITLE
似乎没考虑局域网访问啊

### ISSUE THREAD

**Issue by xflcx1991** [bosichong/PrimarySchoolMathematics#7]
当给vite传递参数让局域网访问时，发现“添加口算题”按钮无效，console控制台有报错

![屏幕截图 2022-12-01 001230](https://user-images.githubusercontent.com/3775351/204850074-d591869a-a78f-4423-84e2-9361b86f4719.png)

![屏幕截图 2022-12-01 001317](https://user-images.githubusercontent.com/3775351/204850431-a7282cac-0655-4b5b-a59d-ec551aae8bbf.png)

**Comment by xflcx1991** [comment]
可以用反代？

**Comment by bosichong** [comment]
跟新了一个版本,你下载试试,然后fastapi启动的时候,设置个局网IP试试.

**Comment by bosichong** [comment]
新版本,把前端打包到fastapi了, 研究一下uvicorn服务器配置就好.
