### ISSUE TITLE
请问这种情况是必须要更换python版本吗，如果不是的话，该怎么解决呢

### ISSUE THREAD

**Issue by 5120205942** [bosichong/PrimarySchoolMathematics#8]
![image](https://user-images.githubusercontent.com/85146396/206484960-313bd26f-f2a8-4a5b-a033-55d9b7e7c128.png)
![image](https://user-images.githubusercontent.com/85146396/206484960-313bd26f-f2a8-4a5b-a033-55d9b7e7c128.png)
![image](https://user-images.githubusercontent.com/85146396/206484960-313bd26f-f2a8-4a5b-a033-55d9b7e7c128.png)

**Comment by YaMaHongDu** [comment]
> ![image](https://user-images.githubusercontent.com/85146396/206484960-313bd26f-f2a8-4a5b-a033-55d9b7e7c128.png) ![image](https://user-images.githubusercontent.com/85146396/206484960-313bd26f-f2a8-4a5b-a033-55d9b7e7c128.png) ![image](https://user-images.githubusercontent.com/85146396/206484960-313bd26f-f2a8-4a5b-a033-55d9b7e7c128.png)

3.9以后的Python版本将【section.py】Line7改成以下：
from collections.abc import Sequence

**Comment by bosichong** [comment]
依赖没有安装好,建议安装相关的依赖,可查阅readme 中有介绍.



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月26日(星期一) 晚上11:48
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [bosichong/PrimarySchoolMathematics] 请问这种情况是必须要更换python版本吗，如果不是的话，该怎么解决呢 (Issue #8)





  
  
  
3.9以后的Python版本将【section.py】Line7改成以下：
 from collections.abc import Sequence
