### ISSUE TITLE
后端服务已经启动了，但是浏览器127.0.0.0:8000还是无法访问

### ISSUE THREAD

**Issue by YaMaHongDu** [bosichong/PrimarySchoolMathematics#9]
请教个问题，就是后端服务已经正常运行了，但是浏览器里输入127.0.0.8000无法访问，但是输入127.0.0.8000 是可以访问到页面，照道理这样说fastapi服务应该是OK的，但是不能访问算数生成页，请问可能会是啥原因呢？
![image](https://user-images.githubusercontent.com/33249480/209566314-2db276e5-4eb8-479d-8da0-3f3045fd868d.png)
![image](https://user-images.githubusercontent.com/33249480/209566363-dc6244ef-04b4-4ab1-82e2-9639554356d9.png)
![image](https://user-images.githubusercontent.com/33249480/209566548-1e471fbc-123b-4f73-a10f-dbae0f26fe1d.png)

**Comment by bosichong** [comment]
安全连接?用的啥浏览器?这个问题,我还真没遇到过.

**Comment by bosichong** [comment]
实在不行,你试试启动一下前端,前后分离试试看.
